/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeu2584;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Sylvain
 */
public class GUI2048 extends javax.swing.JFrame implements Parametres, KeyListener  {

    private Grille g, g2;
    JPanel[] panelsCasesJ1;
    JPanel[] panelsCasesJ2;

    /**
     * Creates new form GUI2048
     */
    public GUI2048() {
        initComponents();
        //this.addKeyListener(this);
        //requestFocusInWindow();
        
        panelsCasesJ1 = new JPanel[16];
        panelsCasesJ1[0] = x0y0_J1;
        panelsCasesJ1[1] = x1y0_J1;
        panelsCasesJ1[2] = x2y0_J1;
        panelsCasesJ1[3] = x3y0_J1;
        panelsCasesJ1[4] = x0y1_J1;
        panelsCasesJ1[5] = x1y1_J1;
        panelsCasesJ1[6] = x2y1_J1;
        panelsCasesJ1[7] = x3y1_J1;
        panelsCasesJ1[8] = x0y2_J1;
        panelsCasesJ1[9] = x1y2_J1;
        panelsCasesJ1[10] = x2y2_J1;
        panelsCasesJ1[11] = x3y2_J1;
        panelsCasesJ1[12] = x0y3_J1;
        panelsCasesJ1[13] = x1y3_J1;
        panelsCasesJ1[14] = x2y3_J1;
        panelsCasesJ1[15] = x3y3_J1;
        
        panelsCasesJ2 = new JPanel[16];
        panelsCasesJ2[0] = x0y0_J2;
        panelsCasesJ2[1] = x1y0_J2;
        panelsCasesJ2[2] = x2y0_J2;
        panelsCasesJ2[3] = x3y0_J2;
        panelsCasesJ2[4] = x0y1_J2;
        panelsCasesJ2[5] = x1y1_J2;
        panelsCasesJ2[6] = x2y1_J2;
        panelsCasesJ2[7] = x3y1_J2;
        panelsCasesJ2[8] = x0y2_J2;
        panelsCasesJ2[9] = x1y2_J2;
        panelsCasesJ2[10] = x2y2_J2;
        panelsCasesJ2[11] = x3y2_J2;
        panelsCasesJ2[12] = x0y3_J2;
        panelsCasesJ2[13] = x1y3_J2;
        panelsCasesJ2[14] = x2y3_J2;
        panelsCasesJ2[15] = x3y3_J2;
        
        g = new Grille();
        boolean bg = g.nouvelleCase();
        bg = g.nouvelleCase();
        
        g2 = new Grille();
        boolean bg2 = g2.nouvelleCase();
        bg2 = g2.nouvelleCase();
        
        
        this.rafraichir();
    }

    private void rafraichir() {
        labelGrille1.setText(g.toHTML());
        labelGrille2.setText(g2.toHTML());
        int[][] tabG1 = g.toTab();
        int[][] tabG2 = g2.toTab();
        
        for (int y = 0; y < tabG1.length; y++) {
            for (int x = 0; x < tabG1.length; x++) {
               JLabel c = (JLabel) panelsCasesJ1[x + y*4].getComponent(0);
               //JPanel p = (JPanel) Grille1.getComp (x + y*4);
               //JLabel c = (JLabel) p.getComponent(0);
               c.setText(Integer.toString(tabG1[y][x]));
            }    
        }
        scoreJ1.setText(Integer.toString(g.getValeurMax()));
        
        for (int y = 0; y < tabG2.length; y++) {
            for (int x = 0; x < tabG2.length; x++) {
               JLabel c = (JLabel) panelsCasesJ2[x + y*4].getComponent(0);
               c.setText(Integer.toString(tabG2[y][x]));
            }    
        }
        scoreJ2.setText(Integer.toString(g2.getValeurMax()));
        
        
        
        
    }

    private void finPartieJ1(String message) {
        resultat.setText(message);
        g.terminerGrille();
        boutonDroite.setEnabled(false);
        boutonGauche.setEnabled(false);
        boutonHaut.setEnabled(false);
        boutonBas.setEnabled(false);
    }
    
    private void finPartieJ2(String message) {
        resultat.setText(message);
        g2.terminerGrille();
        boutonDroite.setEnabled(false);
        boutonGauche.setEnabled(false);
        boutonHaut.setEnabled(false);
        boutonBas.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonHaut = new javax.swing.JButton();
        boutonGauche = new javax.swing.JButton();
        boutonDroite = new javax.swing.JButton();
        boutonBas = new javax.swing.JButton();
        resultat = new javax.swing.JLabel();
        labelGrille1 = new javax.swing.JLabel();
        labelGrille2 = new javax.swing.JLabel();
        Grille1 = new javax.swing.JPanel();
        x0y0_J1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        x0y1_J1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        x0y2_J1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        x0y3_J1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        x1y0_J1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        x1y1_J1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        x1y2_J1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        x1y3_J1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        x2y0_J1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        x2y1_J1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        x2y2_J1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        x2y3_J1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        x3y0_J1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        x3y1_J1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        x3y2_J1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        x3y3_J1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Grille2 = new javax.swing.JPanel();
        x0y0_J2 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        x0y1_J2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        x0y2_J2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        x0y3_J2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        x1y0_J2 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        x1y1_J2 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        x1y2_J2 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        x1y3_J2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        x2y0_J2 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        x2y1_J2 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        x2y2_J2 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        x2y3_J2 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        x3y0_J2 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        x3y1_J2 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        x3y2_J2 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        x3y3_J2 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        scoreJ1 = new javax.swing.JLabel();
        labelScoreJ1 = new javax.swing.JLabel();
        scoreJ2 = new javax.swing.JLabel();
        labelScoreJ2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        boutonHaut.setText("^");
        boutonHaut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonHautMouseClicked(evt);
            }
        });

        boutonGauche.setText("<");
        boutonGauche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonGaucheMouseClicked(evt);
            }
        });

        boutonDroite.setText(">");
        boutonDroite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonDroiteMouseClicked(evt);
            }
        });

        boutonBas.setText("v");
        boutonBas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonBasMouseClicked(evt);
            }
        });

        labelGrille1.setBackground(new java.awt.Color(153, 153, 153));
        labelGrille1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelGrille2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Grille1.setBackground(new java.awt.Color(102, 102, 102));
        Grille1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x0y0_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel32.setText("1");

        javax.swing.GroupLayout x0y0_J1Layout = new javax.swing.GroupLayout(x0y0_J1);
        x0y0_J1.setLayout(x0y0_J1Layout);
        x0y0_J1Layout.setHorizontalGroup(
            x0y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y0_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y0_J1Layout.setVerticalGroup(
            x0y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y0_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y1_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel28.setText("1");

        javax.swing.GroupLayout x0y1_J1Layout = new javax.swing.GroupLayout(x0y1_J1);
        x0y1_J1.setLayout(x0y1_J1Layout);
        x0y1_J1Layout.setHorizontalGroup(
            x0y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y1_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        x0y1_J1Layout.setVerticalGroup(
            x0y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y1_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y2_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel21.setText("1");

        javax.swing.GroupLayout x0y2_J1Layout = new javax.swing.GroupLayout(x0y2_J1);
        x0y2_J1.setLayout(x0y2_J1Layout);
        x0y2_J1Layout.setHorizontalGroup(
            x0y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y2_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y2_J1Layout.setVerticalGroup(
            x0y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y2_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y3_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("1");

        javax.swing.GroupLayout x0y3_J1Layout = new javax.swing.GroupLayout(x0y3_J1);
        x0y3_J1.setLayout(x0y3_J1Layout);
        x0y3_J1Layout.setHorizontalGroup(
            x0y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y3_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y3_J1Layout.setVerticalGroup(
            x0y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y3_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y0_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel33.setText("1");

        javax.swing.GroupLayout x1y0_J1Layout = new javax.swing.GroupLayout(x1y0_J1);
        x1y0_J1.setLayout(x1y0_J1Layout);
        x1y0_J1Layout.setHorizontalGroup(
            x1y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y0_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y0_J1Layout.setVerticalGroup(
            x1y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y0_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y1_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel29.setText("1");

        javax.swing.GroupLayout x1y1_J1Layout = new javax.swing.GroupLayout(x1y1_J1);
        x1y1_J1.setLayout(x1y1_J1Layout);
        x1y1_J1Layout.setHorizontalGroup(
            x1y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y1_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        x1y1_J1Layout.setVerticalGroup(
            x1y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y1_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y2_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel22.setText("1");

        javax.swing.GroupLayout x1y2_J1Layout = new javax.swing.GroupLayout(x1y2_J1);
        x1y2_J1.setLayout(x1y2_J1Layout);
        x1y2_J1Layout.setHorizontalGroup(
            x1y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y2_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y2_J1Layout.setVerticalGroup(
            x1y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y2_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y3_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setText("1");

        javax.swing.GroupLayout x1y3_J1Layout = new javax.swing.GroupLayout(x1y3_J1);
        x1y3_J1.setLayout(x1y3_J1Layout);
        x1y3_J1Layout.setHorizontalGroup(
            x1y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y3_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y3_J1Layout.setVerticalGroup(
            x1y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y3_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y0_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel34.setText("1");

        javax.swing.GroupLayout x2y0_J1Layout = new javax.swing.GroupLayout(x2y0_J1);
        x2y0_J1.setLayout(x2y0_J1Layout);
        x2y0_J1Layout.setHorizontalGroup(
            x2y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y0_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y0_J1Layout.setVerticalGroup(
            x2y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y0_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y1_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel30.setText("1");

        javax.swing.GroupLayout x2y1_J1Layout = new javax.swing.GroupLayout(x2y1_J1);
        x2y1_J1.setLayout(x2y1_J1Layout);
        x2y1_J1Layout.setHorizontalGroup(
            x2y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y1_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        x2y1_J1Layout.setVerticalGroup(
            x2y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y1_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y2_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel27.setText("1");

        javax.swing.GroupLayout x2y2_J1Layout = new javax.swing.GroupLayout(x2y2_J1);
        x2y2_J1.setLayout(x2y2_J1Layout);
        x2y2_J1Layout.setHorizontalGroup(
            x2y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y2_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y2_J1Layout.setVerticalGroup(
            x2y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y2_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y3_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setText("1");

        javax.swing.GroupLayout x2y3_J1Layout = new javax.swing.GroupLayout(x2y3_J1);
        x2y3_J1.setLayout(x2y3_J1Layout);
        x2y3_J1Layout.setHorizontalGroup(
            x2y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y3_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y3_J1Layout.setVerticalGroup(
            x2y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y3_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y0_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel35.setText("1");

        javax.swing.GroupLayout x3y0_J1Layout = new javax.swing.GroupLayout(x3y0_J1);
        x3y0_J1.setLayout(x3y0_J1Layout);
        x3y0_J1Layout.setHorizontalGroup(
            x3y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y0_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y0_J1Layout.setVerticalGroup(
            x3y0_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y0_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y1_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel31.setText("1");

        javax.swing.GroupLayout x3y1_J1Layout = new javax.swing.GroupLayout(x3y1_J1);
        x3y1_J1.setLayout(x3y1_J1Layout);
        x3y1_J1Layout.setHorizontalGroup(
            x3y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y1_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y1_J1Layout.setVerticalGroup(
            x3y1_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y1_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y2_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setText("1");

        javax.swing.GroupLayout x3y2_J1Layout = new javax.swing.GroupLayout(x3y2_J1);
        x3y2_J1.setLayout(x3y2_J1Layout);
        x3y2_J1Layout.setHorizontalGroup(
            x3y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y2_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y2_J1Layout.setVerticalGroup(
            x3y2_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y2_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y3_J1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setText("1");

        javax.swing.GroupLayout x3y3_J1Layout = new javax.swing.GroupLayout(x3y3_J1);
        x3y3_J1.setLayout(x3y3_J1Layout);
        x3y3_J1Layout.setHorizontalGroup(
            x3y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y3_J1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y3_J1Layout.setVerticalGroup(
            x3y3_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y3_J1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout Grille1Layout = new javax.swing.GroupLayout(Grille1);
        Grille1.setLayout(Grille1Layout);
        Grille1Layout.setHorizontalGroup(
            Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Grille1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Grille1Layout.createSequentialGroup()
                        .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Grille1Layout.createSequentialGroup()
                                .addComponent(x0y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Grille1Layout.createSequentialGroup()
                                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x0y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x0y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(x1y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x1y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2y0_J1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x2y1_J1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(x2y2_J1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Grille1Layout.createSequentialGroup()
                        .addComponent(x0y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x1y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(x2y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x3y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Grille1Layout.setVerticalGroup(
            Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Grille1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x0y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y0_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Grille1Layout.createSequentialGroup()
                        .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x1y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x1y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Grille1Layout.createSequentialGroup()
                        .addComponent(x2y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x2y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Grille1Layout.createSequentialGroup()
                        .addComponent(x3y1_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x3y2_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Grille1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(x2y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(x3y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(x0y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1y3_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Grille2.setBackground(new java.awt.Color(102, 102, 102));
        Grille2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x0y0_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel51.setText("1");

        javax.swing.GroupLayout x0y0_J2Layout = new javax.swing.GroupLayout(x0y0_J2);
        x0y0_J2.setLayout(x0y0_J2Layout);
        x0y0_J2Layout.setHorizontalGroup(
            x0y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y0_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y0_J2Layout.setVerticalGroup(
            x0y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y0_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y1_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel52.setText("1");

        javax.swing.GroupLayout x0y1_J2Layout = new javax.swing.GroupLayout(x0y1_J2);
        x0y1_J2.setLayout(x0y1_J2Layout);
        x0y1_J2Layout.setHorizontalGroup(
            x0y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y1_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        x0y1_J2Layout.setVerticalGroup(
            x0y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y1_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y2_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel53.setText("1");

        javax.swing.GroupLayout x0y2_J2Layout = new javax.swing.GroupLayout(x0y2_J2);
        x0y2_J2.setLayout(x0y2_J2Layout);
        x0y2_J2Layout.setHorizontalGroup(
            x0y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y2_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y2_J2Layout.setVerticalGroup(
            x0y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y2_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x0y3_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("1");

        javax.swing.GroupLayout x0y3_J2Layout = new javax.swing.GroupLayout(x0y3_J2);
        x0y3_J2.setLayout(x0y3_J2Layout);
        x0y3_J2Layout.setHorizontalGroup(
            x0y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0y3_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x0y3_J2Layout.setVerticalGroup(
            x0y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x0y3_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y0_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel54.setText("1");

        javax.swing.GroupLayout x1y0_J2Layout = new javax.swing.GroupLayout(x1y0_J2);
        x1y0_J2.setLayout(x1y0_J2Layout);
        x1y0_J2Layout.setHorizontalGroup(
            x1y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y0_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y0_J2Layout.setVerticalGroup(
            x1y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y0_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y1_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel55.setText("1");

        javax.swing.GroupLayout x1y1_J2Layout = new javax.swing.GroupLayout(x1y1_J2);
        x1y1_J2.setLayout(x1y1_J2Layout);
        x1y1_J2Layout.setHorizontalGroup(
            x1y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y1_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        x1y1_J2Layout.setVerticalGroup(
            x1y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y1_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y2_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel56.setText("1");

        javax.swing.GroupLayout x1y2_J2Layout = new javax.swing.GroupLayout(x1y2_J2);
        x1y2_J2.setLayout(x1y2_J2Layout);
        x1y2_J2Layout.setHorizontalGroup(
            x1y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y2_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y2_J2Layout.setVerticalGroup(
            x1y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y2_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x1y3_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel57.setText("1");

        javax.swing.GroupLayout x1y3_J2Layout = new javax.swing.GroupLayout(x1y3_J2);
        x1y3_J2.setLayout(x1y3_J2Layout);
        x1y3_J2Layout.setHorizontalGroup(
            x1y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1y3_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x1y3_J2Layout.setVerticalGroup(
            x1y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x1y3_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y0_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel58.setText("1");

        javax.swing.GroupLayout x2y0_J2Layout = new javax.swing.GroupLayout(x2y0_J2);
        x2y0_J2.setLayout(x2y0_J2Layout);
        x2y0_J2Layout.setHorizontalGroup(
            x2y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y0_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y0_J2Layout.setVerticalGroup(
            x2y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y0_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y1_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel59.setText("1");

        javax.swing.GroupLayout x2y1_J2Layout = new javax.swing.GroupLayout(x2y1_J2);
        x2y1_J2.setLayout(x2y1_J2Layout);
        x2y1_J2Layout.setHorizontalGroup(
            x2y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y1_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        x2y1_J2Layout.setVerticalGroup(
            x2y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y1_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y2_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel60.setText("1");

        javax.swing.GroupLayout x2y2_J2Layout = new javax.swing.GroupLayout(x2y2_J2);
        x2y2_J2.setLayout(x2y2_J2Layout);
        x2y2_J2Layout.setHorizontalGroup(
            x2y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y2_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y2_J2Layout.setVerticalGroup(
            x2y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y2_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x2y3_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel61.setText("1");

        javax.swing.GroupLayout x2y3_J2Layout = new javax.swing.GroupLayout(x2y3_J2);
        x2y3_J2.setLayout(x2y3_J2Layout);
        x2y3_J2Layout.setHorizontalGroup(
            x2y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2y3_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x2y3_J2Layout.setVerticalGroup(
            x2y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x2y3_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y0_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel62.setText("1");

        javax.swing.GroupLayout x3y0_J2Layout = new javax.swing.GroupLayout(x3y0_J2);
        x3y0_J2.setLayout(x3y0_J2Layout);
        x3y0_J2Layout.setHorizontalGroup(
            x3y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y0_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y0_J2Layout.setVerticalGroup(
            x3y0_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y0_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y1_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel63.setText("1");

        javax.swing.GroupLayout x3y1_J2Layout = new javax.swing.GroupLayout(x3y1_J2);
        x3y1_J2.setLayout(x3y1_J2Layout);
        x3y1_J2Layout.setHorizontalGroup(
            x3y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y1_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y1_J2Layout.setVerticalGroup(
            x3y1_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y1_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y2_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel64.setText("1");

        javax.swing.GroupLayout x3y2_J2Layout = new javax.swing.GroupLayout(x3y2_J2);
        x3y2_J2.setLayout(x3y2_J2Layout);
        x3y2_J2Layout.setHorizontalGroup(
            x3y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y2_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y2_J2Layout.setVerticalGroup(
            x3y2_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y2_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        x3y3_J2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel65.setText("1");

        javax.swing.GroupLayout x3y3_J2Layout = new javax.swing.GroupLayout(x3y3_J2);
        x3y3_J2.setLayout(x3y3_J2Layout);
        x3y3_J2Layout.setHorizontalGroup(
            x3y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3y3_J2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        x3y3_J2Layout.setVerticalGroup(
            x3y3_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x3y3_J2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout Grille2Layout = new javax.swing.GroupLayout(Grille2);
        Grille2.setLayout(Grille2Layout);
        Grille2Layout.setHorizontalGroup(
            Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Grille2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Grille2Layout.createSequentialGroup()
                        .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Grille2Layout.createSequentialGroup()
                                .addComponent(x0y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Grille2Layout.createSequentialGroup()
                                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x0y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x0y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(x1y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x1y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2y0_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x2y1_J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(x2y2_J2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Grille2Layout.createSequentialGroup()
                        .addComponent(x0y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x1y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(x2y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x3y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Grille2Layout.setVerticalGroup(
            Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Grille2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x0y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3y0_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Grille2Layout.createSequentialGroup()
                        .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x1y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x1y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Grille2Layout.createSequentialGroup()
                        .addComponent(x2y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x2y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Grille2Layout.createSequentialGroup()
                        .addComponent(x3y1_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x3y2_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Grille2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(x2y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(x3y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(x0y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1y3_J2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        scoreJ1.setBackground(new java.awt.Color(204, 204, 0));
        scoreJ1.setText("test");

        labelScoreJ1.setText("Score Joueur 1 :");

        scoreJ2.setBackground(new java.awt.Color(204, 204, 0));
        scoreJ2.setText("test");

        labelScoreJ2.setText("Score Joueur 2 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelScoreJ1)
                    .addComponent(boutonGauche))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(boutonDroite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelScoreJ2)
                        .addGap(18, 18, 18)
                        .addComponent(scoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boutonHaut)
                    .addComponent(boutonBas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Grille1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelGrille1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Grille2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labelGrille2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(resultat, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(labelGrille1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(Grille1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Grille2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(labelGrille2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelScoreJ1)
                    .addComponent(scoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelScoreJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(boutonHaut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonGauche)
                    .addComponent(boutonDroite))
                .addGap(3, 3, 3)
                .addComponent(boutonBas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonHautMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonHautMouseClicked
        // TODO add your handling code here:
        if (boutonHaut.isEnabled()) {
            boolean b2 = g.lanceurDeplacerCases(HAUT);
            if (b2) {
                boolean b = g.nouvelleCase();
                if (!b) {
                    this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
                }
            }
            this.rafraichir();
            if (g.getValeurMax() >= OBJECTIF) {
                this.finPartieJ1("Gagné ! Score = "+g.getValeurMax());
            }
            if (g.partieFinie()) this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
        }
    }//GEN-LAST:event_boutonHautMouseClicked

    private void boutonGaucheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonGaucheMouseClicked
        // TODO add your handling code here:
        if (boutonGauche.isEnabled()) {
            boolean b2 = g.lanceurDeplacerCases(GAUCHE);
            if (b2) {
                boolean b = g.nouvelleCase();
                if (!b) {
                    this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
                }
            }
            this.rafraichir();
            if (g.getValeurMax() >= OBJECTIF) {
                this.finPartieJ1("Gagné ! Score = "+g.getValeurMax());
            }
            if (g.partieFinie()) this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
        }
    }//GEN-LAST:event_boutonGaucheMouseClicked

    private void boutonDroiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonDroiteMouseClicked
        // TODO add your handling code here:
        if (boutonDroite.isEnabled()) {
            boolean b2 = g.lanceurDeplacerCases(DROITE);
            if (b2) {
                boolean b = g.nouvelleCase();
                if (!b) {
                    this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
                }
            }
            this.rafraichir();
            if (g.getValeurMax() >= OBJECTIF) {
                this.finPartieJ1("Gagné ! Score = "+g.getValeurMax());
            }
            if (g.partieFinie()) this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
        }
    }//GEN-LAST:event_boutonDroiteMouseClicked

    private void boutonBasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonBasMouseClicked
        // TODO add your handling code here:
        if (boutonBas.isEnabled()) {
            boolean b2 = g.lanceurDeplacerCases(BAS);
            if (b2) {
                boolean b = g.nouvelleCase();
                if (!b) {
                    this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
                }
            }
            this.rafraichir();
            if (g.getValeurMax() >= OBJECTIF) {
                this.finPartieJ1("Gagné ! Score = "+g.getValeurMax());
            }
            if (g.partieFinie()) this.finPartieJ1("Perdu ! Score = "+g.getValeurMax());
        }
    }//GEN-LAST:event_boutonBasMouseClicked
    
    @Override
    public void keyTyped(KeyEvent e) {
        System.out.println(e);    
    }
    
    @Override
    public void keyReleased(KeyEvent e) {
        System.out.println(e);      
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println(e);
        int codeDeLaTouche = e.getKeyCode();
        switch (codeDeLaTouche) // Les valeurs sont contenue dans KeyEvent. Elles commencent par VK_ et finissent par le nom de la touche
        {
            case KeyEvent.VK_UP: // si la touche enfoncée est celle du haut
                fonctionPourMonter();
                break;
            case KeyEvent.VK_LEFT: // si la touche enfoncée est celle de gauche
                fonctionPourAllerAGauche();
                break;
            case KeyEvent.VK_RIGHT: // si la touche enfoncée est celle de droite
                fonctionPourAllerADroite();
                break;
            case KeyEvent.VK_DOWN: // si la touche enfoncée est celle du bas
                fonctionPourDescendre();
                break;
        }
    }
    
    private void fonctionPourMonter() {                                        
        // TODO add your handling code here:
        boolean b2 = g2.lanceurDeplacerCases(HAUT);
        if (b2) {
            boolean b = g2.nouvelleCase();
            if (!b) {
                this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
            }
        }
        this.rafraichir();
        if (g2.getValeurMax() >= OBJECTIF) {
            this.finPartieJ2("Gagné Joueur 2 ! Score = "+g2.getValeurMax());
        }
        if (g2.partieFinie()) this.finPartieJ2("Perdu Joueur 2 ! Score = "+g2.getValeurMax());
        
    }                                       

    private void fonctionPourAllerAGauche() {                                          
        // TODO add your handling code here:
        
        boolean b2 = g2.lanceurDeplacerCases(GAUCHE);
        if (b2) {
            boolean b = g2.nouvelleCase();
            if (!b) {
                this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
            }
        }
        this.rafraichir();
        if (g2.getValeurMax() >= OBJECTIF) {
            this.finPartieJ2("Gagné Joueur 2! Score = "+g2.getValeurMax());
        }
        if (g2.partieFinie()) this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
        
    }                                         

    private void fonctionPourAllerADroite() {                                          
        // TODO add your handling code here:
        boolean b2 = g2.lanceurDeplacerCases(DROITE);
        if (b2) {
            boolean b = g2.nouvelleCase();
            if (!b) {
                this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
            }
        }
        this.rafraichir();
        if (g2.getValeurMax() >= OBJECTIF) {
            this.finPartieJ2("Gagné Joueur 2! Score = "+g2.getValeurMax());
        }
        if (g2.partieFinie()) this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
    }                                         

    private void fonctionPourDescendre() {                                       
        // TODO add your handling code here:
        boolean b2 = g2.lanceurDeplacerCases(BAS);
        if (b2) {
            boolean b = g2.nouvelleCase();
            if (!b) {
                this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
            }
        }
        this.rafraichir();
        if (g2.getValeurMax() >= OBJECTIF) {
            this.finPartieJ2("Gagné Joueur 2! Score = "+g2.getValeurMax());
        }
        if (g2.partieFinie()) this.finPartieJ2("Perdu Joueur 2! Score = "+g2.getValeurMax());
    } 

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2048().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grille1;
    private javax.swing.JPanel Grille2;
    private javax.swing.JButton boutonBas;
    private javax.swing.JButton boutonDroite;
    private javax.swing.JButton boutonGauche;
    private javax.swing.JButton boutonHaut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelGrille1;
    private javax.swing.JLabel labelGrille2;
    private javax.swing.JLabel labelScoreJ1;
    private javax.swing.JLabel labelScoreJ2;
    private javax.swing.JLabel resultat;
    private javax.swing.JLabel scoreJ1;
    private javax.swing.JLabel scoreJ2;
    private javax.swing.JPanel x0y0_J1;
    private javax.swing.JPanel x0y0_J2;
    private javax.swing.JPanel x0y1_J1;
    private javax.swing.JPanel x0y1_J2;
    private javax.swing.JPanel x0y2_J1;
    private javax.swing.JPanel x0y2_J2;
    private javax.swing.JPanel x0y3_J1;
    private javax.swing.JPanel x0y3_J2;
    private javax.swing.JPanel x1y0_J1;
    private javax.swing.JPanel x1y0_J2;
    private javax.swing.JPanel x1y1_J1;
    private javax.swing.JPanel x1y1_J2;
    private javax.swing.JPanel x1y2_J1;
    private javax.swing.JPanel x1y2_J2;
    private javax.swing.JPanel x1y3_J1;
    private javax.swing.JPanel x1y3_J2;
    private javax.swing.JPanel x2y0_J1;
    private javax.swing.JPanel x2y0_J2;
    private javax.swing.JPanel x2y1_J1;
    private javax.swing.JPanel x2y1_J2;
    private javax.swing.JPanel x2y2_J1;
    private javax.swing.JPanel x2y2_J2;
    private javax.swing.JPanel x2y3_J1;
    private javax.swing.JPanel x2y3_J2;
    private javax.swing.JPanel x3y0_J1;
    private javax.swing.JPanel x3y0_J2;
    private javax.swing.JPanel x3y1_J1;
    private javax.swing.JPanel x3y1_J2;
    private javax.swing.JPanel x3y2_J1;
    private javax.swing.JPanel x3y2_J2;
    private javax.swing.JPanel x3y3_J1;
    private javax.swing.JPanel x3y3_J2;
    // End of variables declaration//GEN-END:variables


    
}
